### ISSUE TITLE
UserEdit falla

### ISSUE THREAD

**Issue by TEMPLARIO1999** [elyak123/construbot#147]
El traceback indica:

**TypeError: __init__() got an unexpected keyword argument 'user'**

Tal vez se está tratando de dar un formulario diferente al usuario debido a que es _Nv. de acceso 1_.

**Comment by TEMPLARIO1999** [comment]
Se arregló parcialmente el error en la rama Carlos, pero se deja abierto el problema. Ya que hace falta **testing** de los formularios y vistas.

**Comment by elyak123** [comment]
Creo que este problema se ha solucionado, actualmente el código que lo valida es:
```
    def get_form_kwargs(self):
        kwargs = super(UserUpdateView, self).get_form_kwargs()
        if self.nivel_permiso_usuario >= self.permiso_requerido:
            if self.kwargs.get('username', None) and self.kwargs.get('username') != self.request.user.username:
                kwargs['user'] = self.object
        return kwargs
```
En caso de que el usuario no tenga suficientes permisos para ver otros usuarios, simplemente le asigna el usuario del request.
