### ISSUE TITLE
A 404 page that allow to the user know if need to change company.

### ISSUE THREAD

**Issue by TEMPLARIO1999** [elyak123/construbot#78]
If a user is administrator and belongs to the same costumer that another user, or contract, or estimate, but in another company, this raises an 404 error page. We need to tell the user have to change the current company to the other that have the wanted instance.

**Comment by elyak123** [comment]
Este issue tiene relación con #135 , en los templates correspondientes a los errores se debe manejar este logica.

**Comment by elyak123** [comment]
Se resolvio con #145 existe una funcion que se llama `get_object_403_or_404` que puede decidir si debemos mostrar un `PermissionDenied` o un 404
